### ISSUE TITLE
Feature 1 - Graphing Total Commits

### ISSUE THREAD

**Issue by DanielMadaghjian** [cpusch/CSU33012-Final-Project-Group-11#1]
# Summary
Create visualization of the total commits over time, from a Github repository

## Action
The Backend Team extract data using Python and Github API from the Github repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui
Using this data, create a graph of total commits over time using React. Create branches off of Dev, and push to these branches, and finally create a pull request to dev branch. Then the infrastructure team will merge this into main. 
## Tasks
- [x] Backend team extract data using Github API. Push to backend branch.
- [x] Frontend Team creates graph from this data using React. Push to frontend branch
- [x] Both frontend and backend team, create pull request to dev branch.
- [x] Merge into main
