### ISSUE TITLE
Add Testing to Backend

### ISSUE THREAD

**Issue by DanielMadaghjian** [cpusch/CSU33012-Final-Project-Group-11#14]
# Summary 
One of the key parts of the CI/CD Pipeline is that we do some testing to ensure that what we're putting in the repo is not breaking. With respect to the backend team, we want to ensure the correct data is being pulled from the API, and is being sent correctly to the frontend team.

## Action
Backend team add testing, using any python testing libraries or frameworks most suited. This will then allow the infrastructure team to create a CI Workflow to automate these tests anytime code is pushed to the dev branch.

## Tasks
- [x] Choose some testing framework, and inform infrastructure team
- [x] Get some basic tests working
- [x] Push to test branch
- [x] Pull request to dev branch
- [x] Develop more tests
