### ISSUE TITLE
Feature 2 - Graphing times to resolve issues 

### ISSUE THREAD

**Issue by DanielMadaghjian** [cpusch/CSU33012-Final-Project-Group-11#2]
# Summary
Create visualizations showing the time taken to resolve issues, for a given Github repository

## Action
The Backend Team extract data using Python and Github API from the Github repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui
Using this data, the Frontend Team create visualizations showing the different times it takes to resolve issues, using React. This could include the likes of a bar chart, showing the average time, maximum time, min time, median time etc. Push this to the feature-2 branch and create pull request to dev branch. Then the infrastructure team will merge this into main. 

## Tasks
- [x] Backend team extract data using Github API. Push to backend branch.
- [x] #9
- [x] Both frontend and backend team, create pull request to dev branch.
- [x] Merge into main
