### ISSUE TITLE
Set up CI/CD Workflow

### ISSUE THREAD

**Issue by DanielMadaghjian** [cpusch/CSU33012-Final-Project-Group-11#3]
# Summary
Infrastructure team, add docker image for both frontend and backend, which will allow us to proceed with the CI/CD Workflow.

## Action
Add a DockerFile to both the frontend folder and backend folder. Push this to the dev branch and merge to main once we are happy.

## Tasks
- [x] Set up DockerFile to Frontend
- [x] Set up DockerFile to backend
- [x] Push this to the dev branch
- [x] Merge into main
